import type { SceneParams } from "@workspace/api-client-react";

export interface CuratedLine {
  text: string;
  scene: SceneParams;
  customScene?: "tiger" | "eye" | "captain";
}

export interface CuratedPoem {
  id: string;
  title: string;
  label?: string;
  author: string;
  year: string;
  themeColor: string;
  accentColor: string;
  description: string;
  lines: CuratedLine[];
}

const S = (p: Partial<SceneParams>): SceneParams => ({
  sceneType: "void",
  skyColor: "#050010",
  fogColor: "#0a0020",
  fogDensity: 0.008,
  groundColor: "#0a0015",
  ambientColor: "#110022",
  lightColor: "#9966ff",
  lightIntensity: 1.5,
  turbulence: 0.1,
  timeOfDay: 0,
  terrain: 0,
  terrainHeight: 3,
  terrainScale: 1.5,
  water: 0,
  waterColor: "#0044cc",
  waterOpacity: 0.8,
  trees: 0,
  treeColor: "#1a5030",
  buildings: 0,
  columns: 0,
  fire: 0,
  particles: 0,
  particleColor: "#ffffff",
  particleSize: 0.06,
  particleCount: 2000,
  particleMotion: "float",
  particleSpread: 30,
  spheres: 0,
  sphereColor: "#8866ff",
  stars: 0,
  rings: 0,
  ringColor: "#cc88ff",
  cameraAngle: "horizon",
  ...p,
});

// ─── BLAKE: The Tyger ────────────────────────────────────────────────────────

const tyger: CuratedPoem = {
  id: "tyger",
  title: "The Tyger",
  author: "William Blake",
  year: "1794",
  themeColor: "#ff6600",
  accentColor: "#ff2200",
  description: "A fearsome creature born of immortal fire — Blake's burning vision of creation and terror.",
  lines: [
    {
      text: "Tyger Tyger, burning bright,",
      customScene: "tiger",
      scene: S({
        sceneType: "fire",
        skyColor: "#0a0200",
        fogColor: "#2a0a00",
        groundColor: "#1a0800",
        ambientColor: "#3a1000",
        lightColor: "#ff8800",
        lightIntensity: 4,
        turbulence: 0.65,
        timeOfDay: 0.02,
        terrain: 0.3,
        terrainHeight: 1.5,
        fire: 1,
        particles: 0.9,
        particleColor: "#ff9900",
        particleSize: 0.05,
        particleCount: 5000,
        particleMotion: "rise",
        particleSpread: 25,
        cameraAngle: "low",
      }),
    },
    {
      text: "In the forests of the night;",
      scene: S({
        sceneType: "forest",
        skyColor: "#000308",
        fogColor: "#010a03",
        groundColor: "#030d05",
        ambientColor: "#001a05",
        lightColor: "#22ff88",
        lightIntensity: 0.7,
        turbulence: 0.08,
        timeOfDay: 0.01,
        terrain: 0.4,
        terrainHeight: 2.5,
        trees: 1,
        treeColor: "#0a2210",
        particles: 0.7,
        particleColor: "#44ff99",
        particleSize: 0.08,
        particleCount: 2500,
        particleMotion: "float",
        particleSpread: 35,
        stars: 0.3,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "What immortal hand or eye,",
      customScene: "eye",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#06001a",
        fogColor: "#0d0028",
        groundColor: "#0a0020",
        ambientColor: "#150030",
        lightColor: "#cc88ff",
        lightIntensity: 1.2,
        turbulence: 0.15,
        timeOfDay: 0,
        particles: 0.5,
        particleColor: "#cc88ff",
        particleSize: 0.04,
        particleCount: 3000,
        particleMotion: "orbit",
        particleSpread: 40,
        spheres: 0.3,
        sphereColor: "#ffffff",
        stars: 0.7,
        rings: 0.6,
        ringColor: "#aa66ff",
        cameraAngle: "wide",
      }),
    },
    {
      text: "Could frame thy fearful symmetry?",
      scene: S({
        sceneType: "void",
        skyColor: "#030010",
        fogColor: "#060020",
        groundColor: "#050010",
        ambientColor: "#0a0020",
        lightColor: "#ff6600",
        lightIntensity: 2,
        turbulence: 0.3,
        timeOfDay: 0,
        particles: 0.6,
        particleColor: "#ff8800",
        particleSize: 0.05,
        particleCount: 4000,
        particleMotion: "orbit",
        particleSpread: 28,
        rings: 1,
        ringColor: "#ff4400",
        spheres: 0.2,
        sphereColor: "#ff6600",
        cameraAngle: "wide",
      }),
    },
    {
      text: "In what distant deeps or skies,",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#000510",
        fogColor: "#000a20",
        groundColor: "#000820",
        ambientColor: "#000530",
        lightColor: "#4488ff",
        lightIntensity: 1,
        turbulence: 0.05,
        timeOfDay: 0,
        stars: 1,
        particles: 0.5,
        particleColor: "#4488ff",
        particleSize: 0.04,
        particleCount: 4000,
        particleMotion: "drift",
        particleSpread: 50,
        spheres: 0.5,
        sphereColor: "#2244cc",
        rings: 0.2,
        cameraAngle: "wide",
      }),
    },
    {
      text: "Burnt the fire of thine eyes?",
      customScene: "tiger",
      scene: S({
        sceneType: "fire",
        skyColor: "#0a0100",
        fogColor: "#1a0500",
        groundColor: "#120300",
        ambientColor: "#2a0500",
        lightColor: "#ff5500",
        lightIntensity: 3.5,
        turbulence: 0.8,
        timeOfDay: 0.02,
        fire: 0.7,
        particles: 1,
        particleColor: "#ffaa00",
        particleSize: 0.06,
        particleCount: 6000,
        particleMotion: "rise",
        particleSpread: 20,
        cameraAngle: "closeup",
      }),
    },
  ],
};

// ─── FROST: The Road Not Taken ───────────────────────────────────────────────

const frost: CuratedPoem = {
  id: "frost",
  title: "The Road Not Taken",
  author: "Robert Frost",
  year: "1916",
  themeColor: "#e8a020",
  accentColor: "#c87820",
  description: "Autumn gold and the eternal question of paths chosen and unchosen, stretching into the wood.",
  lines: [
    {
      text: "Two roads diverged in a yellow wood,",
      scene: S({
        sceneType: "forest",
        skyColor: "#b87820",
        fogColor: "#8a5510",
        groundColor: "#6a3a08",
        ambientColor: "#9a6010",
        lightColor: "#ffd060",
        lightIntensity: 2.5,
        turbulence: 0.08,
        timeOfDay: 0.75,
        terrain: 0.6,
        terrainHeight: 2,
        terrainScale: 2,
        trees: 0.9,
        treeColor: "#e0880a",
        particles: 0.55,
        particleColor: "#ffa500",
        particleSize: 0.1,
        particleCount: 1800,
        particleMotion: "float",
        particleSpread: 40,
        cameraAngle: "wide",
      }),
    },
    {
      text: "And sorry I could not travel both",
      scene: S({
        sceneType: "forest",
        skyColor: "#7a5008",
        fogColor: "#5a3806",
        groundColor: "#4a2a05",
        ambientColor: "#6a4208",
        lightColor: "#dda030",
        lightIntensity: 1.8,
        turbulence: 0.05,
        timeOfDay: 0.7,
        terrain: 0.5,
        terrainHeight: 1.5,
        trees: 0.85,
        treeColor: "#c87010",
        particles: 0.35,
        particleColor: "#dd8800",
        particleSize: 0.09,
        particleCount: 1200,
        particleMotion: "drift",
        particleSpread: 35,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "And be one traveler, long I stood",
      scene: S({
        sceneType: "forest",
        skyColor: "#6a4a06",
        fogColor: "#3a2504",
        groundColor: "#3a2005",
        ambientColor: "#5a3a06",
        lightColor: "#cc9020",
        lightIntensity: 1.4,
        turbulence: 0.02,
        timeOfDay: 0.65,
        terrain: 0.4,
        terrainHeight: 1.2,
        trees: 0.95,
        treeColor: "#b86208",
        particles: 0.15,
        particleColor: "#cc8800",
        particleSize: 0.08,
        particleCount: 800,
        particleMotion: "still",
        particleSpread: 30,
        cameraAngle: "closeup",
      }),
    },
    {
      text: "And looked down one as far as I could",
      scene: S({
        sceneType: "forest",
        skyColor: "#5a3a08",
        fogColor: "#2a1a04",
        groundColor: "#2a1a04",
        ambientColor: "#4a2a06",
        lightColor: "#bb8010",
        lightIntensity: 1.6,
        turbulence: 0.04,
        timeOfDay: 0.6,
        terrain: 0.7,
        terrainHeight: 3,
        terrainScale: 0.8,
        trees: 1,
        treeColor: "#aa5508",
        particles: 0.4,
        particleColor: "#bb7700",
        particleSize: 0.07,
        particleCount: 1400,
        particleMotion: "float",
        particleSpread: 45,
        cameraAngle: "wide",
      }),
    },
    {
      text: "To where it bent in the undergrowth.",
      scene: S({
        sceneType: "forest",
        skyColor: "#2a1a04",
        fogColor: "#150e02",
        groundColor: "#1a1206",
        ambientColor: "#2a1a06",
        lightColor: "#884400",
        lightIntensity: 0.9,
        turbulence: 0.06,
        timeOfDay: 0.55,
        terrain: 0.8,
        terrainHeight: 4,
        terrainScale: 3,
        trees: 1,
        treeColor: "#1a4010",
        particles: 0.5,
        particleColor: "#2a6020",
        particleSize: 0.06,
        particleCount: 1600,
        particleMotion: "drift",
        particleSpread: 20,
        cameraAngle: "closeup",
      }),
    },
  ],
};

// ─── NERUDA: Tonight I Can Write ─────────────────────────────────────────────

const neruda: CuratedPoem = {
  id: "neruda",
  title: "Tonight I Can Write",
  author: "Pablo Neruda",
  year: "1924",
  themeColor: "#4466cc",
  accentColor: "#8899ff",
  description: "Starlit grief dissolving into the infinite night — love remembered across a vast and trembling cosmos.",
  lines: [
    {
      text: "Tonight I can write the saddest lines.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010510",
        fogColor: "#020818",
        groundColor: "#020815",
        ambientColor: "#050a20",
        lightColor: "#6688cc",
        lightIntensity: 0.6,
        turbulence: 0.08,
        timeOfDay: 0,
        stars: 0.85,
        particles: 0.6,
        particleColor: "#7799cc",
        particleSize: 0.04,
        particleCount: 3500,
        particleMotion: "drift",
        particleSpread: 50,
        rings: 0.25,
        ringColor: "#334488",
        cameraAngle: "wide",
      }),
    },
    {
      text: "Write, for example, 'The night is starry,",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010310",
        fogColor: "#010520",
        groundColor: "#010520",
        ambientColor: "#020830",
        lightColor: "#8899ff",
        lightIntensity: 0.8,
        turbulence: 0.04,
        timeOfDay: 0,
        stars: 1,
        particles: 0.3,
        particleColor: "#eeeeff",
        particleSize: 0.025,
        particleCount: 4000,
        particleMotion: "still",
        particleSpread: 55,
        spheres: 0.2,
        sphereColor: "#aabbff",
        cameraAngle: "wide",
      }),
    },
    {
      text: "and the stars shiver, blue, in the distance.'",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010820",
        fogColor: "#010a30",
        groundColor: "#010a28",
        ambientColor: "#020f38",
        lightColor: "#5577ff",
        lightIntensity: 1.0,
        turbulence: 0.2,
        timeOfDay: 0,
        stars: 0.8,
        particles: 0.65,
        particleColor: "#5577ff",
        particleSize: 0.045,
        particleCount: 4000,
        particleMotion: "pulse",
        particleSpread: 48,
        spheres: 0.45,
        sphereColor: "#3355ee",
        rings: 0.15,
        ringColor: "#2244cc",
        cameraAngle: "wide",
      }),
    },
    {
      text: "The night wind revolves in the sky and sings.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#020814",
        fogColor: "#030c22",
        groundColor: "#030c20",
        ambientColor: "#050f28",
        lightColor: "#88aaee",
        lightIntensity: 0.9,
        turbulence: 0.45,
        timeOfDay: 0,
        stars: 0.7,
        particles: 0.75,
        particleColor: "#99bbff",
        particleSize: 0.04,
        particleCount: 4500,
        particleMotion: "spiral",
        particleSpread: 40,
        rings: 0.55,
        ringColor: "#6688dd",
        cameraAngle: "wide",
      }),
    },
    {
      text: "I loved her, and sometimes she loved me too.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#080518",
        fogColor: "#0d0828",
        groundColor: "#0d0820",
        ambientColor: "#100a28",
        lightColor: "#dd88bb",
        lightIntensity: 1.1,
        turbulence: 0.12,
        timeOfDay: 0,
        stars: 0.6,
        particles: 0.5,
        particleColor: "#ff99cc",
        particleSize: 0.06,
        particleCount: 2500,
        particleMotion: "orbit",
        particleSpread: 35,
        spheres: 0.7,
        sphereColor: "#cc66aa",
        rings: 0.3,
        ringColor: "#ff88cc",
        cameraAngle: "horizon",
      }),
    },
    {
      text: "Tonight I can write the saddest lines.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010408",
        fogColor: "#010612",
        groundColor: "#010610",
        ambientColor: "#020918",
        lightColor: "#5566aa",
        lightIntensity: 0.5,
        turbulence: 0.1,
        timeOfDay: 0,
        stars: 0.95,
        particles: 0.8,
        particleColor: "#6677bb",
        particleSize: 0.035,
        particleCount: 5000,
        particleMotion: "drift",
        particleSpread: 55,
        rings: 0.4,
        ringColor: "#334477",
        cameraAngle: "wide",
      }),
    },
  ],
};

// ─── WHITMAN: O Captain! My Captain! ─────────────────────────────────────────

const whitman: CuratedPoem = {
  id: "whitman",
  title: "O Captain! My Captain!",
  author: "Walt Whitman",
  year: "1865",
  themeColor: "#4499cc",
  accentColor: "#cc2244",
  description: "A nation's triumph shadowed by grief — surging ocean waves and the silence of a fallen hero.",
  lines: [
    {
      text: "O Captain! my Captain! our fearful trip is done,",
      customScene: "captain",
      scene: S({
        sceneType: "ocean",
        skyColor: "#0a1535",
        fogColor: "#0d1e45",
        groundColor: "#050d20",
        ambientColor: "#0a1530",
        lightColor: "#88bbff",
        lightIntensity: 1.8,
        turbulence: 0.35,
        timeOfDay: 0.85,
        terrain: 0.1,
        water: 0.9,
        waterColor: "#0a2860",
        waterOpacity: 0.9,
        particles: 0.4,
        particleColor: "#aaccff",
        particleSize: 0.06,
        particleCount: 2000,
        particleMotion: "drift",
        particleSpread: 45,
        stars: 0.4,
        cameraAngle: "wide",
      }),
    },
    {
      text: "The ship has weather'd every rack, the prize we sought is won,",
      scene: S({
        sceneType: "ocean",
        skyColor: "#1a1530",
        fogColor: "#1a1f40",
        groundColor: "#060d1a",
        ambientColor: "#101828",
        lightColor: "#ddcc66",
        lightIntensity: 2.2,
        turbulence: 0.5,
        timeOfDay: 0.8,
        water: 0.85,
        waterColor: "#0d2550",
        waterOpacity: 0.85,
        particles: 0.45,
        particleColor: "#ddcc66",
        particleSize: 0.07,
        particleCount: 2200,
        particleMotion: "rise",
        particleSpread: 40,
        stars: 0.3,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "The port is near, the bells I hear, the people all exulting,",
      scene: S({
        sceneType: "city",
        skyColor: "#080f28",
        fogColor: "#0a1430",
        groundColor: "#050a18",
        ambientColor: "#0a1228",
        lightColor: "#ffdd88",
        lightIntensity: 1.5,
        turbulence: 0.15,
        timeOfDay: 0.2,
        buildings: 0.7,
        particles: 0.55,
        particleColor: "#ffee88",
        particleSize: 0.08,
        particleCount: 2500,
        particleMotion: "float",
        particleSpread: 45,
        stars: 0.35,
        cameraAngle: "low",
      }),
    },
    {
      text: "But O heart! heart! heart!",
      scene: S({
        sceneType: "void",
        skyColor: "#080005",
        fogColor: "#100008",
        groundColor: "#0a0005",
        ambientColor: "#120008",
        lightColor: "#cc1133",
        lightIntensity: 1.2,
        turbulence: 0.25,
        timeOfDay: 0,
        particles: 0.4,
        particleColor: "#dd1133",
        particleSize: 0.07,
        particleCount: 2000,
        particleMotion: "pulse",
        particleSpread: 22,
        spheres: 0.25,
        sphereColor: "#aa0022",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "O the bleeding drops of red,",
      scene: S({
        sceneType: "void",
        skyColor: "#050002",
        fogColor: "#0a0003",
        groundColor: "#080003",
        ambientColor: "#0d0005",
        lightColor: "#cc0011",
        lightIntensity: 1.5,
        turbulence: 0.4,
        timeOfDay: 0,
        particles: 0.7,
        particleColor: "#dd0011",
        particleSize: 0.06,
        particleCount: 4000,
        particleMotion: "rain",
        particleSpread: 30,
        fire: 0.25,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "Where on the deck my Captain lies,",
      scene: S({
        sceneType: "ocean",
        skyColor: "#020508",
        fogColor: "#040810",
        groundColor: "#030810",
        ambientColor: "#050a14",
        lightColor: "#6688aa",
        lightIntensity: 0.6,
        turbulence: 0.15,
        timeOfDay: 0.05,
        water: 0.4,
        waterColor: "#06142a",
        waterOpacity: 0.7,
        particles: 0.2,
        particleColor: "#7799bb",
        particleSize: 0.04,
        particleCount: 1200,
        particleMotion: "drift",
        particleSpread: 40,
        stars: 0.2,
        cameraAngle: "low",
      }),
    },
  ],
};

// ─── INDOVINA: Weight ─────────────────────────────────────────────────────────
// Prose poem embodying a bison — earthy, primal, heavy, chemical

const weight: CuratedPoem = {
  id: "weight",
  label: "Weight",
  title: "Weight",
  author: "Indovina",
  year: "2024",
  themeColor: "#b07030",
  accentColor: "#8a4a10",
  description: "A body becomes a bison — weight, herd-smell, mud, and the chemical heat of being alive.",
  lines: [
    {
      text: "Today I am weight. Today my tail quivers with the herd's, a burly",
      scene: S({
        sceneType: "forest",
        skyColor: "#100800",
        fogColor: "#1a0c02",
        fogDensity: 0.018,
        groundColor: "#3a1f04",
        ambientColor: "#2a1404",
        lightColor: "#d08020",
        lightIntensity: 1.2,
        turbulence: 0.35,
        timeOfDay: 0.15,
        terrain: 0.7,
        terrainHeight: 1.2,
        terrainScale: 2.5,
        particles: 0.8,
        particleColor: "#c8a040",
        particleSize: 0.07,
        particleCount: 3000,
        particleMotion: "drift",
        particleSpread: 45,
        trees: 0.2,
        treeColor: "#2a1a04",
        cameraAngle: "low",
      }),
    },
    {
      text: "pack of cattails swirling. I am big-bellied, furry, untamable. I am",
      scene: S({
        sceneType: "forest",
        skyColor: "#0c0a00",
        fogColor: "#1a1400",
        fogDensity: 0.022,
        groundColor: "#2a1e00",
        ambientColor: "#221200",
        lightColor: "#c09010",
        lightIntensity: 0.9,
        turbulence: 0.55,
        timeOfDay: 0.08,
        terrain: 0.5,
        terrainHeight: 1.8,
        terrainScale: 2.0,
        particles: 1,
        particleColor: "#b89040",
        particleSize: 0.09,
        particleCount: 5000,
        particleMotion: "orbit",
        particleSpread: 30,
        trees: 0.4,
        treeColor: "#1a1200",
        cameraAngle: "low",
      }),
    },
    {
      text: "full of grass. Today I get to think about my next meal. Today I",
      scene: S({
        sceneType: "forest",
        skyColor: "#0a1800",
        fogColor: "#0e2200",
        fogDensity: 0.01,
        groundColor: "#1e3a00",
        ambientColor: "#122800",
        lightColor: "#88d030",
        lightIntensity: 1.8,
        turbulence: 0.1,
        timeOfDay: 0.5,
        terrain: 0.8,
        terrainHeight: 0.8,
        terrainScale: 3.5,
        trees: 0.6,
        treeColor: "#1a4000",
        particles: 0.3,
        particleColor: "#aaee44",
        particleSize: 0.05,
        particleCount: 1200,
        particleMotion: "float",
        particleSpread: 50,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "daydream about the rut, strutting and curling my lip, grunting with",
      scene: S({
        sceneType: "fire",
        skyColor: "#0a0200",
        fogColor: "#1e0800",
        fogDensity: 0.025,
        groundColor: "#1a0800",
        ambientColor: "#300800",
        lightColor: "#ff5500",
        lightIntensity: 3.5,
        turbulence: 0.75,
        timeOfDay: 0.02,
        terrain: 0.3,
        terrainHeight: 1.0,
        fire: 0.7,
        particles: 0.9,
        particleColor: "#ff7700",
        particleSize: 0.07,
        particleCount: 4000,
        particleMotion: "rise",
        particleSpread: 20,
        cameraAngle: "low",
      }),
    },
    {
      text: "my tongue outstretched. Today I want to wallow in the mud with",
      scene: S({
        sceneType: "ocean",
        skyColor: "#080500",
        fogColor: "#100a00",
        fogDensity: 0.03,
        groundColor: "#150a00",
        ambientColor: "#0c0500",
        lightColor: "#7a5020",
        lightIntensity: 0.7,
        turbulence: 0.2,
        timeOfDay: 0.08,
        water: 0.8,
        waterColor: "#2a1400",
        waterOpacity: 0.95,
        particles: 0.4,
        particleColor: "#6a4010",
        particleSize: 0.06,
        particleCount: 1500,
        particleMotion: "drift",
        particleSpread: 25,
        cameraAngle: "low",
      }),
    },
    {
      text: "all the other lip-curlers, licking pheromonal heat. Shuffle of",
      scene: S({
        sceneType: "void",
        skyColor: "#080003",
        fogColor: "#100008",
        fogDensity: 0.015,
        groundColor: "#0a0005",
        ambientColor: "#120008",
        lightColor: "#ff88aa",
        lightIntensity: 1.5,
        turbulence: 0.45,
        timeOfDay: 0,
        particles: 1,
        particleColor: "#ffaa44",
        particleSize: 0.05,
        particleCount: 6000,
        particleMotion: "pulse",
        particleSpread: 35,
        spheres: 0.15,
        sphereColor: "#ff6688",
        cameraAngle: "wide",
      }),
    },
    {
      text: "salivating verve. Scruff of soul. Today I hoist my bulging bulk. My",
      scene: S({
        sceneType: "void",
        skyColor: "#0c0500",
        fogColor: "#180a00",
        fogDensity: 0.012,
        groundColor: "#100800",
        ambientColor: "#1a0a00",
        lightColor: "#d07020",
        lightIntensity: 2.5,
        turbulence: 0.5,
        timeOfDay: 0,
        particles: 0.85,
        particleColor: "#c08820",
        particleSize: 0.08,
        particleCount: 4500,
        particleMotion: "rise",
        particleSpread: 28,
        spheres: 0.3,
        sphereColor: "#b07030",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "nose twitches with distant splays of sweat. Ears infused in",
      scene: S({
        sceneType: "void",
        skyColor: "#040404",
        fogColor: "#080804",
        fogDensity: 0.008,
        groundColor: "#060602",
        ambientColor: "#0a0a04",
        lightColor: "#e0c060",
        lightIntensity: 0.8,
        turbulence: 0.08,
        timeOfDay: 0,
        particles: 0.6,
        particleColor: "#d4b844",
        particleSize: 0.03,
        particleCount: 4000,
        particleMotion: "scatter",
        particleSpread: 60,
        cameraAngle: "wide",
      }),
    },
    {
      text: "chemical cues. I am nature, never devil. Today I give my love",
      scene: S({
        sceneType: "forest",
        skyColor: "#050d00",
        fogColor: "#0a1800",
        fogDensity: 0.006,
        groundColor: "#142800",
        ambientColor: "#0c1e00",
        lightColor: "#90dd44",
        lightIntensity: 1.4,
        turbulence: 0.12,
        timeOfDay: 0.35,
        terrain: 0.9,
        terrainHeight: 0.6,
        terrainScale: 4.0,
        trees: 0.3,
        treeColor: "#1a3800",
        particles: 0.5,
        particleColor: "#c8ee66",
        particleSize: 0.04,
        particleCount: 2000,
        particleMotion: "float",
        particleSpread: 55,
        stars: 0.2,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "away.",
      scene: S({
        sceneType: "void",
        skyColor: "#020200",
        fogColor: "#050500",
        fogDensity: 0.005,
        groundColor: "#030300",
        ambientColor: "#060600",
        lightColor: "#d0a030",
        lightIntensity: 0.5,
        turbulence: 0.04,
        timeOfDay: 0,
        particles: 0.3,
        particleColor: "#d4a840",
        particleSize: 0.04,
        particleCount: 1500,
        particleMotion: "scatter",
        particleSpread: 70,
        cameraAngle: "wide",
      }),
    },
  ],
};

// ─── BRADFORD KIMBALL: Warm for a fish ───────────────────────────────────────
// A fish gutted with reverence — cold water, visceral, strangely tender

const fish: CuratedPoem = {
  id: "fish",
  label: "Warm for a fish",
  title: "Warm for a fish",
  author: "Bradford Kimball",
  year: "2024",
  themeColor: "#2255aa",
  accentColor: "#88ccdd",
  description: "A fisherman guts a great fish with devotion. Cold creek, red waders, whispered reverence.",
  lines: [
    {
      text: "Warm for a fish,",
      scene: S({
        sceneType: "ocean",
        skyColor: "#030810",
        fogColor: "#050e18",
        fogDensity: 0.014,
        groundColor: "#040c16",
        ambientColor: "#060e18",
        lightColor: "#4488bb",
        lightIntensity: 0.9,
        turbulence: 0.06,
        timeOfDay: 0.1,
        water: 0.7,
        waterColor: "#0a2040",
        waterOpacity: 0.85,
        particles: 0.4,
        particleColor: "#6699cc",
        particleSize: 0.04,
        particleCount: 2000,
        particleMotion: "drift",
        particleSpread: 40,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "The kingqueen of egglayers,",
      scene: S({
        sceneType: "ocean",
        skyColor: "#020510",
        fogColor: "#040818",
        fogDensity: 0.016,
        groundColor: "#030714",
        ambientColor: "#050a18",
        lightColor: "#44ddcc",
        lightIntensity: 1.6,
        turbulence: 0.1,
        timeOfDay: 0.05,
        water: 0.9,
        waterColor: "#082840",
        waterOpacity: 0.75,
        particles: 0.7,
        particleColor: "#88eedd",
        particleSize: 0.05,
        particleCount: 4000,
        particleMotion: "float",
        particleSpread: 35,
        spheres: 0.4,
        sphereColor: "#aaddcc",
        rings: 0.4,
        ringColor: "#66ccbb",
        cameraAngle: "wide",
      }),
    },
    {
      text: "Innards sluicing round deckheight",
      scene: S({
        sceneType: "void",
        skyColor: "#080000",
        fogColor: "#120000",
        fogDensity: 0.022,
        groundColor: "#0e0000",
        ambientColor: "#160000",
        lightColor: "#cc2200",
        lightIntensity: 1.8,
        turbulence: 0.3,
        timeOfDay: 0,
        particles: 0.9,
        particleColor: "#aa1100",
        particleSize: 0.07,
        particleCount: 4000,
        particleMotion: "rain",
        particleSpread: 20,
        cameraAngle: "high",
      }),
    },
    {
      text: "Stain the waders of a bearded fisherman.",
      scene: S({
        sceneType: "ocean",
        skyColor: "#040808",
        fogColor: "#080f0f",
        fogDensity: 0.018,
        groundColor: "#060c0c",
        ambientColor: "#080e0e",
        lightColor: "#bb3311",
        lightIntensity: 1.2,
        turbulence: 0.15,
        timeOfDay: 0.12,
        water: 0.5,
        waterColor: "#1a0808",
        waterOpacity: 0.9,
        particles: 0.6,
        particleColor: "#cc2200",
        particleSize: 0.06,
        particleCount: 3000,
        particleMotion: "drift",
        particleSpread: 30,
        cameraAngle: "low",
      }),
    },
    {
      text: "He slices clean the belly",
      scene: S({
        sceneType: "void",
        skyColor: "#060608",
        fogColor: "#0a0a0c",
        fogDensity: 0.010,
        groundColor: "#080810",
        ambientColor: "#0a0a14",
        lightColor: "#eeeeff",
        lightIntensity: 3.0,
        turbulence: 0.05,
        timeOfDay: 0,
        particles: 0.2,
        particleColor: "#ffffff",
        particleSize: 0.03,
        particleCount: 800,
        particleMotion: "still",
        particleSpread: 15,
        rings: 0.3,
        ringColor: "#ccccff",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "With a curved tip razorknife gently,",
      scene: S({
        sceneType: "void",
        skyColor: "#040408",
        fogColor: "#060608",
        fogDensity: 0.008,
        groundColor: "#060608",
        ambientColor: "#08080e",
        lightColor: "#ddddff",
        lightIntensity: 2.5,
        turbulence: 0.04,
        timeOfDay: 0,
        particles: 0.15,
        particleColor: "#ccddff",
        particleSize: 0.025,
        particleCount: 600,
        particleMotion: "still",
        particleSpread: 10,
        rings: 0.8,
        ringColor: "#aabbee",
        spheres: 0.1,
        sphereColor: "#ccddff",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "Calls her gorgeous, kisses",
      scene: S({
        sceneType: "ocean",
        skyColor: "#080404",
        fogColor: "#100808",
        fogDensity: 0.012,
        groundColor: "#0c0606",
        ambientColor: "#100808",
        lightColor: "#ff8844",
        lightIntensity: 1.4,
        turbulence: 0.08,
        timeOfDay: 0.18,
        water: 0.3,
        waterColor: "#1a0c0c",
        waterOpacity: 0.6,
        particles: 0.35,
        particleColor: "#ffaa66",
        particleSize: 0.05,
        particleCount: 1200,
        particleMotion: "float",
        particleSpread: 28,
        cameraAngle: "closeup",
      }),
    },
    {
      text: "Her whiskers whispers creekside",
      scene: S({
        sceneType: "ocean",
        skyColor: "#020608",
        fogColor: "#040a0e",
        fogDensity: 0.02,
        groundColor: "#030808",
        ambientColor: "#040a0a",
        lightColor: "#448866",
        lightIntensity: 0.7,
        turbulence: 0.04,
        timeOfDay: 0.22,
        water: 0.6,
        waterColor: "#06180e",
        waterOpacity: 0.7,
        particles: 0.3,
        particleColor: "#66aa88",
        particleSize: 0.035,
        particleCount: 1000,
        particleMotion: "drift",
        particleSpread: 22,
        cameraAngle: "low",
      }),
    },
    {
      text: "admiral admiral admiral admiral.",
      scene: S({
        sceneType: "void",
        skyColor: "#020408",
        fogColor: "#030610",
        fogDensity: 0.010,
        groundColor: "#020510",
        ambientColor: "#040818",
        lightColor: "#4466bb",
        lightIntensity: 1.5,
        turbulence: 0.12,
        timeOfDay: 0,
        particles: 0.5,
        particleColor: "#6688cc",
        particleSize: 0.04,
        particleCount: 2500,
        particleMotion: "orbit",
        particleSpread: 25,
        rings: 1,
        ringColor: "#3355aa",
        spheres: 0.2,
        sphereColor: "#4466bb",
        stars: 0.4,
        cameraAngle: "wide",
      }),
    },
    {
      text: "She expects that every man",
      scene: S({
        sceneType: "ocean",
        skyColor: "#020408",
        fogColor: "#040810",
        fogDensity: 0.015,
        groundColor: "#030710",
        ambientColor: "#040a14",
        lightColor: "#3355aa",
        lightIntensity: 0.6,
        turbulence: 0.05,
        timeOfDay: 0.05,
        water: 0.8,
        waterColor: "#06101e",
        waterOpacity: 0.9,
        particles: 0.25,
        particleColor: "#5577aa",
        particleSize: 0.04,
        particleCount: 1000,
        particleMotion: "drift",
        particleSpread: 45,
        stars: 0.3,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "Will do his slicing right.",
      scene: S({
        sceneType: "void",
        skyColor: "#020202",
        fogColor: "#040404",
        fogDensity: 0.008,
        groundColor: "#030303",
        ambientColor: "#050505",
        lightColor: "#ffffff",
        lightIntensity: 4.5,
        turbulence: 0.02,
        timeOfDay: 0,
        particles: 0.1,
        particleColor: "#eeeeff",
        particleSize: 0.02,
        particleCount: 400,
        particleMotion: "still",
        particleSpread: 8,
        rings: 0.2,
        ringColor: "#ffffff",
        cameraAngle: "closeup",
      }),
    },
  ],
};

// ─── LINDSEY WAYLAND: Day Forty-Two ───────────────────────────────────────────
// A haiku — storm → blackout → candlelight. Three scenes, three worlds.

const haiku: CuratedPoem = {
  id: "haiku",
  label: "Day Forty-Two",
  title: "Day Forty-Two",
  author: "Lindsey Wayland",
  year: "2024",
  themeColor: "#ff9944",
  accentColor: "#cc5500",
  description: "A winter windstorm kills the power. Three lines. Three worlds.",
  lines: [
    {
      text: "A winter windstorm",
      scene: S({
        sceneType: "void",
        skyColor: "#0e0e12",
        fogColor: "#141418",
        fogDensity: 0.035,
        groundColor: "#0c0c10",
        ambientColor: "#101014",
        lightColor: "#aabbdd",
        lightIntensity: 0.5,
        turbulence: 0.95,
        timeOfDay: 0.15,
        particles: 1,
        particleColor: "#ccddee",
        particleSize: 0.04,
        particleCount: 8000,
        particleMotion: "scatter",
        particleSpread: 55,
        cameraAngle: "wide",
      }),
    },
    {
      text: "blows down the power lines. We",
      scene: S({
        sceneType: "void",
        skyColor: "#010102",
        fogColor: "#020204",
        fogDensity: 0.04,
        groundColor: "#010103",
        ambientColor: "#020204",
        lightColor: "#334455",
        lightIntensity: 0.25,
        turbulence: 0.15,
        timeOfDay: 0,
        particles: 0.2,
        particleColor: "#445566",
        particleSize: 0.03,
        particleCount: 600,
        particleMotion: "drift",
        particleSpread: 40,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "eat by candlelight.",
      scene: S({
        sceneType: "fire",
        skyColor: "#060200",
        fogColor: "#0e0500",
        fogDensity: 0.04,
        groundColor: "#0c0400",
        ambientColor: "#120800",
        lightColor: "#ff8820",
        lightIntensity: 3.0,
        turbulence: 0.1,
        timeOfDay: 0,
        fire: 0.35,
        particles: 0.5,
        particleColor: "#ffbb44",
        particleSize: 0.04,
        particleCount: 1500,
        particleMotion: "rise",
        particleSpread: 8,
        cameraAngle: "closeup",
      }),
    },
  ],
};

// ─── NICHOLAS ALTI: Have You Not Learned I Shall Not Learn? ───────────────────
// Surreal fragmented cosmos — body horror, vortices, Osiris, unexpected glee

const alti: CuratedPoem = {
  id: "alti",
  label: "Have You Not Learned",
  title: "Have You Not Learned I Shall Not Learn?",
  author: "Nicholas Alti",
  year: "2024",
  themeColor: "#8855ff",
  accentColor: "#cc44ff",
  description: "Soul, flare, reckoning. Polyps of personage, prions, Osiris, and glee.",
  lines: [
    {
      text: "Soul or flare, or then a reckoning. Spare pasts",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#04000e",
        fogColor: "#080018",
        fogDensity: 0.008,
        groundColor: "#060010",
        ambientColor: "#0a0020",
        lightColor: "#cc88ff",
        lightIntensity: 3.5,
        turbulence: 0.2,
        timeOfDay: 0,
        particles: 0.3,
        particleColor: "#aa66ff",
        particleSize: 0.04,
        particleCount: 1500,
        particleMotion: "pulse",
        particleSpread: 30,
        rings: 0.8,
        ringColor: "#9955ff",
        stars: 0.5,
        cameraAngle: "wide",
      }),
    },
    {
      text: "from gashes prior. Polyps of personage,",
      scene: S({
        sceneType: "void",
        skyColor: "#020a00",
        fogColor: "#041200",
        fogDensity: 0.015,
        groundColor: "#040c00",
        ambientColor: "#060e00",
        lightColor: "#66cc44",
        lightIntensity: 1.0,
        turbulence: 0.3,
        timeOfDay: 0,
        particles: 0.5,
        particleColor: "#44aa22",
        particleSize: 0.09,
        particleCount: 2500,
        particleMotion: "pulse",
        particleSpread: 22,
        spheres: 0.7,
        sphereColor: "#335522",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "like tight-packed parcels, plucked apart until",
      scene: S({
        sceneType: "void",
        skyColor: "#060008",
        fogColor: "#0a0012",
        fogDensity: 0.012,
        groundColor: "#080010",
        ambientColor: "#0c0018",
        lightColor: "#ee66ff",
        lightIntensity: 2.0,
        turbulence: 0.7,
        timeOfDay: 0,
        particles: 1,
        particleColor: "#dd55ee",
        particleSize: 0.05,
        particleCount: 7000,
        particleMotion: "scatter",
        particleSpread: 50,
        spheres: 0.2,
        sphereColor: "#cc44dd",
        cameraAngle: "wide",
      }),
    },
    {
      text: "raw as small carcass ready for forks.",
      scene: S({
        sceneType: "void",
        skyColor: "#080000",
        fogColor: "#100000",
        fogDensity: 0.018,
        groundColor: "#0c0000",
        ambientColor: "#140000",
        lightColor: "#dd2200",
        lightIntensity: 1.8,
        turbulence: 0.15,
        timeOfDay: 0,
        particles: 0.4,
        particleColor: "#cc1100",
        particleSize: 0.06,
        particleCount: 1800,
        particleMotion: "still",
        particleSpread: 18,
        spheres: 0.5,
        sphereColor: "#aa0000",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "In a butter time—pre-present, future eventual—",
      scene: S({
        sceneType: "void",
        skyColor: "#080600",
        fogColor: "#100c00",
        fogDensity: 0.008,
        groundColor: "#0c0800",
        ambientColor: "#141000",
        lightColor: "#ffdd88",
        lightIntensity: 2.0,
        turbulence: 0.03,
        timeOfDay: 0,
        particles: 0.6,
        particleColor: "#ffcc44",
        particleSize: 0.05,
        particleCount: 3000,
        particleMotion: "still",
        particleSpread: 40,
        spheres: 0.3,
        sphereColor: "#ddaa22",
        cameraAngle: "wide",
      }),
    },
    {
      text: "a pickaxe couldn't puncture them,",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#020408",
        fogColor: "#040810",
        fogDensity: 0.010,
        groundColor: "#030710",
        ambientColor: "#040a14",
        lightColor: "#4477cc",
        lightIntensity: 1.2,
        turbulence: 0.05,
        timeOfDay: 0,
        particles: 0.3,
        particleColor: "#5588dd",
        particleSize: 0.03,
        particleCount: 1500,
        particleMotion: "still",
        particleSpread: 35,
        spheres: 0.8,
        sphereColor: "#335599",
        rings: 0.5,
        ringColor: "#2244aa",
        stars: 0.6,
        cameraAngle: "wide",
      }),
    },
    {
      text: "warlords would run away. Partial coordinates",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#030006",
        fogColor: "#060010",
        fogDensity: 0.009,
        groundColor: "#040008",
        ambientColor: "#080014",
        lightColor: "#8833cc",
        lightIntensity: 1.0,
        turbulence: 0.1,
        timeOfDay: 0,
        particles: 0.4,
        particleColor: "#6622aa",
        particleSize: 0.03,
        particleCount: 2000,
        particleMotion: "drift",
        particleSpread: 55,
        stars: 0.8,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "given to an inescapable whorl",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#040010",
        fogColor: "#080020",
        fogDensity: 0.010,
        groundColor: "#060018",
        ambientColor: "#0a0022",
        lightColor: "#6644ff",
        lightIntensity: 2.5,
        turbulence: 0.6,
        timeOfDay: 0,
        particles: 0.9,
        particleColor: "#5533ee",
        particleSize: 0.04,
        particleCount: 6000,
        particleMotion: "spiral",
        particleSpread: 40,
        rings: 0.6,
        ringColor: "#4422dd",
        stars: 0.3,
        cameraAngle: "wide",
      }),
    },
    {
      text: "of vortices. Where portals pulse like swollen",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#030010",
        fogColor: "#060020",
        fogDensity: 0.010,
        groundColor: "#050018",
        ambientColor: "#080022",
        lightColor: "#44ddcc",
        lightIntensity: 3.0,
        turbulence: 0.5,
        timeOfDay: 0,
        particles: 0.7,
        particleColor: "#33ccbb",
        particleSize: 0.05,
        particleCount: 4000,
        particleMotion: "pulse",
        particleSpread: 32,
        rings: 1,
        ringColor: "#22bbaa",
        spheres: 0.4,
        sphereColor: "#33ccbb",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "spores. Starlight a soft no",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010104",
        fogColor: "#020208",
        fogDensity: 0.004,
        groundColor: "#020206",
        ambientColor: "#030308",
        lightColor: "#8899cc",
        lightIntensity: 0.4,
        turbulence: 0.04,
        timeOfDay: 0,
        particles: 0.15,
        particleColor: "#aabbdd",
        particleSize: 0.025,
        particleCount: 700,
        particleMotion: "still",
        particleSpread: 65,
        stars: 0.9,
        cameraAngle: "wide",
      }),
    },
    {
      text: "among firm certainties. Spent parts compose.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#020208",
        fogColor: "#040410",
        fogDensity: 0.006,
        groundColor: "#030310",
        ambientColor: "#050518",
        lightColor: "#9988ff",
        lightIntensity: 1.2,
        turbulence: 0.12,
        timeOfDay: 0,
        particles: 0.55,
        particleColor: "#8877ee",
        particleSize: 0.035,
        particleCount: 3000,
        particleMotion: "float",
        particleSpread: 42,
        stars: 0.5,
        cameraAngle: "wide",
      }),
    },
    {
      text: "Bereft reports galore.",
      scene: S({
        sceneType: "void",
        skyColor: "#020204",
        fogColor: "#030308",
        fogDensity: 0.006,
        groundColor: "#020206",
        ambientColor: "#040408",
        lightColor: "#556677",
        lightIntensity: 0.3,
        turbulence: 0.03,
        timeOfDay: 0,
        particles: 0.1,
        particleColor: "#445566",
        particleSize: 0.02,
        particleCount: 400,
        particleMotion: "drift",
        particleSpread: 70,
        cameraAngle: "wide",
      }),
    },
    {
      text: "A prion named Osiris. Three halves of actual",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#030200",
        fogColor: "#060400",
        fogDensity: 0.008,
        groundColor: "#050300",
        ambientColor: "#080600",
        lightColor: "#cc9900",
        lightIntensity: 1.6,
        turbulence: 0.2,
        timeOfDay: 0,
        particles: 0.4,
        particleColor: "#aa8800",
        particleSize: 0.04,
        particleCount: 2200,
        particleMotion: "orbit",
        particleSpread: 30,
        rings: 0.7,
        ringColor: "#996600",
        spheres: 0.4,
        sphereColor: "#bb9900",
        stars: 0.7,
        cameraAngle: "wide",
      }),
    },
    {
      text: "mysterious. Glee",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#020410",
        fogColor: "#040818",
        fogDensity: 0.005,
        groundColor: "#030614",
        ambientColor: "#060a1e",
        lightColor: "#ffee44",
        lightIntensity: 5.0,
        turbulence: 0.8,
        timeOfDay: 0,
        particles: 1,
        particleColor: "#ffdd22",
        particleSize: 0.06,
        particleCount: 8000,
        particleMotion: "scatter",
        particleSpread: 60,
        spheres: 0.5,
        sphereColor: "#ff9900",
        rings: 0.5,
        ringColor: "#ffcc00",
        stars: 0.8,
        cameraAngle: "wide",
      }),
    },
  ],
};

export const CURATED_POEMS: CuratedPoem[] = [tyger, frost, neruda, whitman, weight, fish, haiku, alti];
