import type { SceneParams } from "@workspace/api-client-react";

export interface CuratedLine {
  text: string;
  scene: SceneParams;
  customScene?: "tiger" | "eye" | "captain";
}

export interface CuratedPoem {
  id: string;
  title: string;
  author: string;
  year: string;
  themeColor: string;
  accentColor: string;
  description: string;
  lines: CuratedLine[];
}

const S = (p: Partial<SceneParams>): SceneParams => ({
  sceneType: "void",
  skyColor: "#050010",
  fogColor: "#0a0020",
  fogDensity: 0.008,
  groundColor: "#0a0015",
  ambientColor: "#110022",
  lightColor: "#9966ff",
  lightIntensity: 1.5,
  turbulence: 0.1,
  timeOfDay: 0,
  terrain: 0,
  terrainHeight: 3,
  terrainScale: 1.5,
  water: 0,
  waterColor: "#0044cc",
  waterOpacity: 0.8,
  trees: 0,
  treeColor: "#1a5030",
  buildings: 0,
  columns: 0,
  fire: 0,
  particles: 0,
  particleColor: "#ffffff",
  particleSize: 0.06,
  particleCount: 2000,
  particleMotion: "float",
  particleSpread: 30,
  spheres: 0,
  sphereColor: "#8866ff",
  stars: 0,
  rings: 0,
  ringColor: "#cc88ff",
  cameraAngle: "horizon",
  ...p,
});

// ─── BLAKE: The Tyger ────────────────────────────────────────────────────────

const tyger: CuratedPoem = {
  id: "tyger",
  title: "The Tyger",
  author: "William Blake",
  year: "1794",
  themeColor: "#ff6600",
  accentColor: "#ff2200",
  description: "A fearsome creature born of immortal fire — Blake's burning vision of creation and terror.",
  lines: [
    {
      text: "Tyger Tyger, burning bright,",
      customScene: "tiger",
      scene: S({
        sceneType: "fire",
        skyColor: "#0a0200",
        fogColor: "#2a0a00",
        groundColor: "#1a0800",
        ambientColor: "#3a1000",
        lightColor: "#ff8800",
        lightIntensity: 4,
        turbulence: 0.65,
        timeOfDay: 0.02,
        terrain: 0.3,
        terrainHeight: 1.5,
        fire: 1,
        particles: 0.9,
        particleColor: "#ff9900",
        particleSize: 0.05,
        particleCount: 5000,
        particleMotion: "rise",
        particleSpread: 25,
        cameraAngle: "low",
      }),
    },
    {
      text: "In the forests of the night;",
      scene: S({
        sceneType: "forest",
        skyColor: "#000308",
        fogColor: "#010a03",
        groundColor: "#030d05",
        ambientColor: "#001a05",
        lightColor: "#22ff88",
        lightIntensity: 0.7,
        turbulence: 0.08,
        timeOfDay: 0.01,
        terrain: 0.4,
        terrainHeight: 2.5,
        trees: 1,
        treeColor: "#0a2210",
        particles: 0.7,
        particleColor: "#44ff99",
        particleSize: 0.08,
        particleCount: 2500,
        particleMotion: "float",
        particleSpread: 35,
        stars: 0.3,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "What immortal hand or eye,",
      customScene: "eye",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#06001a",
        fogColor: "#0d0028",
        groundColor: "#0a0020",
        ambientColor: "#150030",
        lightColor: "#cc88ff",
        lightIntensity: 1.2,
        turbulence: 0.15,
        timeOfDay: 0,
        particles: 0.5,
        particleColor: "#cc88ff",
        particleSize: 0.04,
        particleCount: 3000,
        particleMotion: "orbit",
        particleSpread: 40,
        spheres: 0.3,
        sphereColor: "#ffffff",
        stars: 0.7,
        rings: 0.6,
        ringColor: "#aa66ff",
        cameraAngle: "wide",
      }),
    },
    {
      text: "Could frame thy fearful symmetry?",
      scene: S({
        sceneType: "void",
        skyColor: "#030010",
        fogColor: "#060020",
        groundColor: "#050010",
        ambientColor: "#0a0020",
        lightColor: "#ff6600",
        lightIntensity: 2,
        turbulence: 0.3,
        timeOfDay: 0,
        particles: 0.6,
        particleColor: "#ff8800",
        particleSize: 0.05,
        particleCount: 4000,
        particleMotion: "orbit",
        particleSpread: 28,
        rings: 1,
        ringColor: "#ff4400",
        spheres: 0.2,
        sphereColor: "#ff6600",
        cameraAngle: "wide",
      }),
    },
    {
      text: "In what distant deeps or skies,",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#000510",
        fogColor: "#000a20",
        groundColor: "#000820",
        ambientColor: "#000530",
        lightColor: "#4488ff",
        lightIntensity: 1,
        turbulence: 0.05,
        timeOfDay: 0,
        stars: 1,
        particles: 0.5,
        particleColor: "#4488ff",
        particleSize: 0.04,
        particleCount: 4000,
        particleMotion: "drift",
        particleSpread: 50,
        spheres: 0.5,
        sphereColor: "#2244cc",
        rings: 0.2,
        cameraAngle: "wide",
      }),
    },
    {
      text: "Burnt the fire of thine eyes?",
      customScene: "tiger",
      scene: S({
        sceneType: "fire",
        skyColor: "#0a0100",
        fogColor: "#1a0500",
        groundColor: "#120300",
        ambientColor: "#2a0500",
        lightColor: "#ff5500",
        lightIntensity: 3.5,
        turbulence: 0.8,
        timeOfDay: 0.02,
        fire: 0.7,
        particles: 1,
        particleColor: "#ffaa00",
        particleSize: 0.06,
        particleCount: 6000,
        particleMotion: "rise",
        particleSpread: 20,
        cameraAngle: "closeup",
      }),
    },
  ],
};

// ─── FROST: The Road Not Taken ───────────────────────────────────────────────

const frost: CuratedPoem = {
  id: "frost",
  title: "The Road Not Taken",
  author: "Robert Frost",
  year: "1916",
  themeColor: "#e8a020",
  accentColor: "#c87820",
  description: "Autumn gold and the eternal question of paths chosen and unchosen, stretching into the wood.",
  lines: [
    {
      text: "Two roads diverged in a yellow wood,",
      scene: S({
        sceneType: "forest",
        skyColor: "#b87820",
        fogColor: "#8a5510",
        groundColor: "#6a3a08",
        ambientColor: "#9a6010",
        lightColor: "#ffd060",
        lightIntensity: 2.5,
        turbulence: 0.08,
        timeOfDay: 0.75,
        terrain: 0.6,
        terrainHeight: 2,
        terrainScale: 2,
        trees: 0.9,
        treeColor: "#e0880a",
        particles: 0.55,
        particleColor: "#ffa500",
        particleSize: 0.1,
        particleCount: 1800,
        particleMotion: "float",
        particleSpread: 40,
        cameraAngle: "wide",
      }),
    },
    {
      text: "And sorry I could not travel both",
      scene: S({
        sceneType: "forest",
        skyColor: "#7a5008",
        fogColor: "#5a3806",
        groundColor: "#4a2a05",
        ambientColor: "#6a4208",
        lightColor: "#dda030",
        lightIntensity: 1.8,
        turbulence: 0.05,
        timeOfDay: 0.7,
        terrain: 0.5,
        terrainHeight: 1.5,
        trees: 0.85,
        treeColor: "#c87010",
        particles: 0.35,
        particleColor: "#dd8800",
        particleSize: 0.09,
        particleCount: 1200,
        particleMotion: "drift",
        particleSpread: 35,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "And be one traveler, long I stood",
      scene: S({
        sceneType: "forest",
        skyColor: "#6a4a06",
        fogColor: "#3a2504",
        groundColor: "#3a2005",
        ambientColor: "#5a3a06",
        lightColor: "#cc9020",
        lightIntensity: 1.4,
        turbulence: 0.02,
        timeOfDay: 0.65,
        terrain: 0.4,
        terrainHeight: 1.2,
        trees: 0.95,
        treeColor: "#b86208",
        particles: 0.15,
        particleColor: "#cc8800",
        particleSize: 0.08,
        particleCount: 800,
        particleMotion: "still",
        particleSpread: 30,
        cameraAngle: "closeup",
      }),
    },
    {
      text: "And looked down one as far as I could",
      scene: S({
        sceneType: "forest",
        skyColor: "#5a3a08",
        fogColor: "#2a1a04",
        groundColor: "#2a1a04",
        ambientColor: "#4a2a06",
        lightColor: "#bb8010",
        lightIntensity: 1.6,
        turbulence: 0.04,
        timeOfDay: 0.6,
        terrain: 0.7,
        terrainHeight: 3,
        terrainScale: 0.8,
        trees: 1,
        treeColor: "#aa5508",
        particles: 0.4,
        particleColor: "#bb7700",
        particleSize: 0.07,
        particleCount: 1400,
        particleMotion: "float",
        particleSpread: 45,
        cameraAngle: "wide",
      }),
    },
    {
      text: "To where it bent in the undergrowth.",
      scene: S({
        sceneType: "forest",
        skyColor: "#2a1a04",
        fogColor: "#150e02",
        groundColor: "#1a1206",
        ambientColor: "#2a1a06",
        lightColor: "#884400",
        lightIntensity: 0.9,
        turbulence: 0.06,
        timeOfDay: 0.55,
        terrain: 0.8,
        terrainHeight: 4,
        terrainScale: 3,
        trees: 1,
        treeColor: "#1a4010",
        particles: 0.5,
        particleColor: "#2a6020",
        particleSize: 0.06,
        particleCount: 1600,
        particleMotion: "drift",
        particleSpread: 20,
        cameraAngle: "closeup",
      }),
    },
  ],
};

// ─── NERUDA: Tonight I Can Write ─────────────────────────────────────────────

const neruda: CuratedPoem = {
  id: "neruda",
  title: "Tonight I Can Write",
  author: "Pablo Neruda",
  year: "1924",
  themeColor: "#4466cc",
  accentColor: "#8899ff",
  description: "Starlit grief dissolving into the infinite night — love remembered across a vast and trembling cosmos.",
  lines: [
    {
      text: "Tonight I can write the saddest lines.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010510",
        fogColor: "#020818",
        groundColor: "#020815",
        ambientColor: "#050a20",
        lightColor: "#6688cc",
        lightIntensity: 0.6,
        turbulence: 0.08,
        timeOfDay: 0,
        stars: 0.85,
        particles: 0.6,
        particleColor: "#7799cc",
        particleSize: 0.04,
        particleCount: 3500,
        particleMotion: "drift",
        particleSpread: 50,
        rings: 0.25,
        ringColor: "#334488",
        cameraAngle: "wide",
      }),
    },
    {
      text: "Write, for example, 'The night is starry,",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010310",
        fogColor: "#010520",
        groundColor: "#010520",
        ambientColor: "#020830",
        lightColor: "#8899ff",
        lightIntensity: 0.8,
        turbulence: 0.04,
        timeOfDay: 0,
        stars: 1,
        particles: 0.3,
        particleColor: "#eeeeff",
        particleSize: 0.025,
        particleCount: 4000,
        particleMotion: "still",
        particleSpread: 55,
        spheres: 0.2,
        sphereColor: "#aabbff",
        cameraAngle: "wide",
      }),
    },
    {
      text: "and the stars shiver, blue, in the distance.'",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010820",
        fogColor: "#010a30",
        groundColor: "#010a28",
        ambientColor: "#020f38",
        lightColor: "#5577ff",
        lightIntensity: 1.0,
        turbulence: 0.2,
        timeOfDay: 0,
        stars: 0.8,
        particles: 0.65,
        particleColor: "#5577ff",
        particleSize: 0.045,
        particleCount: 4000,
        particleMotion: "pulse",
        particleSpread: 48,
        spheres: 0.45,
        sphereColor: "#3355ee",
        rings: 0.15,
        ringColor: "#2244cc",
        cameraAngle: "wide",
      }),
    },
    {
      text: "The night wind revolves in the sky and sings.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#020814",
        fogColor: "#030c22",
        groundColor: "#030c20",
        ambientColor: "#050f28",
        lightColor: "#88aaee",
        lightIntensity: 0.9,
        turbulence: 0.45,
        timeOfDay: 0,
        stars: 0.7,
        particles: 0.75,
        particleColor: "#99bbff",
        particleSize: 0.04,
        particleCount: 4500,
        particleMotion: "spiral",
        particleSpread: 40,
        rings: 0.55,
        ringColor: "#6688dd",
        cameraAngle: "wide",
      }),
    },
    {
      text: "I loved her, and sometimes she loved me too.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#080518",
        fogColor: "#0d0828",
        groundColor: "#0d0820",
        ambientColor: "#100a28",
        lightColor: "#dd88bb",
        lightIntensity: 1.1,
        turbulence: 0.12,
        timeOfDay: 0,
        stars: 0.6,
        particles: 0.5,
        particleColor: "#ff99cc",
        particleSize: 0.06,
        particleCount: 2500,
        particleMotion: "orbit",
        particleSpread: 35,
        spheres: 0.7,
        sphereColor: "#cc66aa",
        rings: 0.3,
        ringColor: "#ff88cc",
        cameraAngle: "horizon",
      }),
    },
    {
      text: "Tonight I can write the saddest lines.",
      scene: S({
        sceneType: "cosmos",
        skyColor: "#010408",
        fogColor: "#010612",
        groundColor: "#010610",
        ambientColor: "#020918",
        lightColor: "#5566aa",
        lightIntensity: 0.5,
        turbulence: 0.1,
        timeOfDay: 0,
        stars: 0.95,
        particles: 0.8,
        particleColor: "#6677bb",
        particleSize: 0.035,
        particleCount: 5000,
        particleMotion: "drift",
        particleSpread: 55,
        rings: 0.4,
        ringColor: "#334477",
        cameraAngle: "wide",
      }),
    },
  ],
};

// ─── WHITMAN: O Captain! My Captain! ─────────────────────────────────────────

const whitman: CuratedPoem = {
  id: "whitman",
  title: "O Captain! My Captain!",
  author: "Walt Whitman",
  year: "1865",
  themeColor: "#4499cc",
  accentColor: "#cc2244",
  description: "A nation's triumph shadowed by grief — surging ocean waves and the silence of a fallen hero.",
  lines: [
    {
      text: "O Captain! my Captain! our fearful trip is done,",
      customScene: "captain",
      scene: S({
        sceneType: "ocean",
        skyColor: "#0a1535",
        fogColor: "#0d1e45",
        groundColor: "#050d20",
        ambientColor: "#0a1530",
        lightColor: "#88bbff",
        lightIntensity: 1.8,
        turbulence: 0.35,
        timeOfDay: 0.85,
        terrain: 0.1,
        water: 0.9,
        waterColor: "#0a2860",
        waterOpacity: 0.9,
        particles: 0.4,
        particleColor: "#aaccff",
        particleSize: 0.06,
        particleCount: 2000,
        particleMotion: "drift",
        particleSpread: 45,
        stars: 0.4,
        cameraAngle: "wide",
      }),
    },
    {
      text: "The ship has weather'd every rack, the prize we sought is won,",
      scene: S({
        sceneType: "ocean",
        skyColor: "#1a1530",
        fogColor: "#1a1f40",
        groundColor: "#060d1a",
        ambientColor: "#101828",
        lightColor: "#ddcc66",
        lightIntensity: 2.2,
        turbulence: 0.5,
        timeOfDay: 0.8,
        water: 0.85,
        waterColor: "#0d2550",
        waterOpacity: 0.85,
        particles: 0.45,
        particleColor: "#ddcc66",
        particleSize: 0.07,
        particleCount: 2200,
        particleMotion: "rise",
        particleSpread: 40,
        stars: 0.3,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "The port is near, the bells I hear, the people all exulting,",
      scene: S({
        sceneType: "city",
        skyColor: "#080f28",
        fogColor: "#0a1430",
        groundColor: "#050a18",
        ambientColor: "#0a1228",
        lightColor: "#ffdd88",
        lightIntensity: 1.5,
        turbulence: 0.15,
        timeOfDay: 0.2,
        buildings: 0.7,
        particles: 0.55,
        particleColor: "#ffee88",
        particleSize: 0.08,
        particleCount: 2500,
        particleMotion: "float",
        particleSpread: 45,
        stars: 0.35,
        cameraAngle: "low",
      }),
    },
    {
      text: "But O heart! heart! heart!",
      scene: S({
        sceneType: "void",
        skyColor: "#080005",
        fogColor: "#100008",
        groundColor: "#0a0005",
        ambientColor: "#120008",
        lightColor: "#cc1133",
        lightIntensity: 1.2,
        turbulence: 0.25,
        timeOfDay: 0,
        particles: 0.4,
        particleColor: "#dd1133",
        particleSize: 0.07,
        particleCount: 2000,
        particleMotion: "pulse",
        particleSpread: 22,
        spheres: 0.25,
        sphereColor: "#aa0022",
        cameraAngle: "closeup",
      }),
    },
    {
      text: "O the bleeding drops of red,",
      scene: S({
        sceneType: "void",
        skyColor: "#050002",
        fogColor: "#0a0003",
        groundColor: "#080003",
        ambientColor: "#0d0005",
        lightColor: "#cc0011",
        lightIntensity: 1.5,
        turbulence: 0.4,
        timeOfDay: 0,
        particles: 0.7,
        particleColor: "#dd0011",
        particleSize: 0.06,
        particleCount: 4000,
        particleMotion: "rain",
        particleSpread: 30,
        fire: 0.25,
        cameraAngle: "horizon",
      }),
    },
    {
      text: "Where on the deck my Captain lies,",
      scene: S({
        sceneType: "ocean",
        skyColor: "#020508",
        fogColor: "#040810",
        groundColor: "#030810",
        ambientColor: "#050a14",
        lightColor: "#6688aa",
        lightIntensity: 0.6,
        turbulence: 0.15,
        timeOfDay: 0.05,
        water: 0.4,
        waterColor: "#06142a",
        waterOpacity: 0.7,
        particles: 0.2,
        particleColor: "#7799bb",
        particleSize: 0.04,
        particleCount: 1200,
        particleMotion: "drift",
        particleSpread: 40,
        stars: 0.2,
        cameraAngle: "low",
      }),
    },
  ],
};

export const CURATED_POEMS: CuratedPoem[] = [tyger, frost, neruda, whitman];
