import type { SceneParams } from "@workspace/api-client-react";

export const DEFAULT_SCENE: SceneParams = {
  sceneType: "cosmos",
  skyColor: "#03050f",
  fogColor: "#0a0d1a",
  fogDensity: 0.006,
  groundColor: "#0d0f1e",
  ambientColor: "#1a1f3a",
  lightColor: "#4466aa",
  lightIntensity: 0.4,
  turbulence: 0.05,
  timeOfDay: 0.0,
  terrain: 0.15,
  terrainHeight: 1.5,
  terrainScale: 2,
  water: 0,
  waterColor: "#0d2137",
  waterOpacity: 0.8,
  trees: 0,
  treeColor: "#1a3320",
  buildings: 0,
  columns: 0,
  fire: 0,
  particles: 0.7,
  particleColor: "#8899cc",
  particleSize: 0.04,
  particleCount: 3000,
  particleMotion: "float",
  particleSpread: 40,
  spheres: 0.3,
  sphereColor: "#4466aa",
  stars: 0.9,
  rings: 0,
  ringColor: "#ffffff",
  cameraAngle: "wide",
};
